name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch
        run: git fetch --prune --unshallow --tags
      - name: Clean tags
        run: git tag -l | xargs git tag -d && git fetch --tags
      - name: Get library version name
        run: echo "BLUETOOTH_LE_VERSION_NAME=$(./gradlew -q printVersionName)" >> $GITHUB_ENV
      - name: Get latest tag from prefix
        run: echo "LATEST_TAG=latest_tag=$(git describe --match "${{ env.BLUETOOTH_LE_VERSION_NAME }}.[0-9]*" --tags --abbrev=0 HEAD --first-parent)" >> $GITHUB_ENV
      - name: Print latest tag
        run: |
          if [ -z "${latest_tag##*$BLUETOOTH_LE_VERSION_NAME*}" ]
          then
            echo "BLUETOOTH_LE_NEW_VERSION=${{ env.BLUETOOTH_LE_VERSION_NAME }}.0" >> $GITHUB_ENV
          else
            echo "BLUETOOTH_LE_NEW_VERSION=${{ env.BLUETOOTH_LE_VERSION_NAME }}.$((${latest_tag##*.} + 1))" >> $GITHUB_ENV
          fi
          echo ${{ env.BLUETOOTH_LE_NEW_VERSION }}



#          echo "Test5"
#          latest_tag=$(git describe --match "${{ env.BLUETOOTH_LE_VERSION_NAME }}.[0-9]*" --tags --abbrev=0 HEAD --first-parent)
#          echo "Test6"
#          if [ -z "${latest_tag##*$BLUETOOTH_LE_VERSION_NAME*}" ]; then export new_version=$BLUETOOTH_LE_VERSION_NAME.0; else export new_version=$BLUETOOTH_LE_VERSION_NAME.$((${latest_tag##*.} + 1)); fi
#          echo $new_version
#          echo ${{ env.new_version }}
#      - name: Bump version and push tag
#        uses: mathieudutour/github-tag-action@v4.5
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          custom_tag: ${{ env.new_version }}